'use client';

import { useTambo } from '@tambo-ai/react';
import { motion } from 'framer-motion';
import { FileText, Sparkles } from 'lucide-react';
import { useEffect, useState } from 'react';

export function PostMortem({ incidentId }: { incidentId: string }) {
  const { thread, sendThreadMessage } = useTambo();
  const [report, setReport] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  useEffect(() => {
    // Auto-generate on mount
    const generate = async () => {
      setIsGenerating(true);
      // Simulate AI generation time
      await new Promise((r) => setTimeout(r, 2000));

      setReport(`
# Incident Post-Mortem Report
**ID**: ${incidentId}
**Date**: ${new Date().toLocaleDateString()}

## 1. Executive Summary
A critical failure in the Payment Gateway (API 500 Errors) caused a 15% drop in successful checkout transactions for approximately 12 minutes. The system was restored to full health following an automated rollback.

## 2. Root Cause Analysis (RCA)
- **Primary Cause**: A bad deployment (v24.5.1) introduced a latency regression in the encryption middleware.
- **Trigger**: Autoscaling event exacerbated the latency, causing connection timeouts.

## 3. Timeline
- **Detected**: 14:02 UTC
- **Diagnosis**: 14:03 UTC (WarRoom AI)
- **Action**: Rollback initiated at 14:04 UTC by SRE.
- **Resolution**: 14:06 UTC.

## 4. Action Items
- [ ] Add latency regression tests to CI/CD pipeline.
- [ ] Increase database connection pool size for bursts.
- [ ] Review autoscaling triggers.
       `);
      setIsGenerating(false);
    };
    generate();
  }, [incidentId]);

  return (
    <div className="w-full bg-white dark:bg-neutral-900 border border-neutral-200 dark:border-neutral-800 rounded-xl p-8 shadow-sm">
      <div className="flex items-center gap-3 mb-6">
        <div className="p-2 bg-purple-500/10 rounded-lg text-purple-500">
          <FileText className="w-5 h-5" />
        </div>
        <div>
          <h2 className="text-xl font-bold text-neutral-900 dark:text-white flex items-center gap-2">
            Automated Post-Mortem
            {isGenerating && <Sparkles className="w-4 h-4 text-purple-500 animate-spin" />}
          </h2>
          <p className="text-sm text-neutral-500">Generated by Data Guard AI using incident logs.</p>
        </div>
      </div>

      {isGenerating ? (
        <div className="space-y-4 animate-pulse">
          <div className="h-4 bg-neutral-100 dark:bg-neutral-800 rounded w-3/4" />
          <div className="h-4 bg-neutral-100 dark:bg-neutral-800 rounded w-1/2" />
          <div className="h-32 bg-neutral-100 dark:bg-neutral-800 rounded w-full" />
        </div>
      ) : (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="prose dark:prose-invert max-w-none text-sm"
        >
          {/* Simple markdown rendering for demo */}
          <div className="whitespace-pre-wrap font-mono text-neutral-600 dark:text-neutral-400">{report}</div>
        </motion.div>
      )}
    </div>
  );
}
